### ISSUE TITLE
Flask: python error

### ISSUE THREAD

**Issue by sylvainfaivre** [HeroCTF/HeroCTF_v5#2]
```
❯ docker run flask
Traceback (most recent call last):
  File "/var/www/app/app.py", line 1, in <module>
    from flask import Flask, Request, Response, make_response
  File "/usr/local/lib/python3.10/dist-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/dist-packages/werkzeug/urls.py)

```

**Comment by sylvainfaivre** [comment]
Dependancy problem explained in https://stackoverflow.com/questions/77213053/why-did-flask-start-failing-with-importerror-cannot-import-name-url-quote-fr

Fixed by setting a hard requirement for werkzeug module, see linked PR.
